ER
Tsuka40408080/MINNNANO pull request #4
Opened 2024-08-08 21:29 UTC by Tsuka40408080

ER図のプルリクエストになります。
添削、よろしくお願いします。

2024-08-09 05:06 UTC, Tsuchiya2 commented
<img width="644" alt="スクリーンショット 2024-08-09 14 02 57" src="https://github.com/user-attachments/assets/599351ec-00cf-49e1-a134-6dd9a676d4e0">

こちらアクセス権限が無いためか閲覧できませんでした。

Gyazoを使って作成したER図のスクリーンショットを撮影していただき、マークダウン形式でコピーした後、コメント欄に貼り付けて、画像が表示される形で共有をお願いできますでしょうか。

以降、何か指摘が合った際は都度最新のER図のスクリーンショットをGyazoで撮影して、マークダウン形式で貼り付けて、最新のER図、ER図の変遷が他の講師でも確認できるようにお願いします。

2024-08-09 14:54 UTC, Tsuka40408080 commented
土屋講師
コメントありがとうございます。お手数お掛けして申し訳ありません。
以後、添付して対応していきます。ご確認をお願いします。
[![Image from Gyazo](https://i.gyazo.com/86226bba9cebe72cda58e1d631cf56d0.png)](https://gyazo.com/86226bba9cebe72cda58e1d631cf56d0)

2024-08-10 08:22 UTC, tarakish requested changes
確認できました。以下コメントです！

---
- Users
  - 認証にはなにかgemを使う予定はありますか？使う予定であれば必要なカラムが不足していそうなので見直してみてください。
- 掲示板と掲示板内の記事は具体的にどういう物が入るのか例をおしえていただけますか？
- name, use_idなどはタイポかと思うので修正をお願いします

2024-08-10 17:55 UTC, Tsuka40408080 commented
宮本講師
コメントありがとうございます。
User→gemはsorceryを使用予定です。それに合わせて追加しております。
[![Image from Gyazo](https://i.gyazo.com/a494f2f4b920b5d0cb3ce7847107be88.png)](https://gyazo.com/a494f2f4b920b5d0cb3ce7847107be88)

タイポの方、修正しております。

掲示板と掲示板内の記事は具体的にどういう物か
→画面遷移図のURLになります。お手数でなければみていただけたら幸いです。
https://www.figma.com/board/dS0Dob3SDjHBjIqyMIlxqO/%E5%8D%92%E6%A5%AD%E5%88%B6%E4%BD%9C?node-id=0-1&t=RhA29IRnmwKkJHdP-0
掲示板→飲み会回避方法　朝、上司が機嫌悪い時など具体的な場面・状況を載せる
掲示板内の記事→場面・開発者の解答対応法を記載・ユーザーのコメント
の形を用意する予定です。

わかりづらく申し訳ありません。確認よろしくお願い致します。

2024-08-13 04:01 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。
修正が必要になった際は適宜修正して開発を進めましょう。

2024-08-14 16:29 UTC, merged